### ISSUE TITLE
Gnome Terminal says a return 0 message.

### ISSUE THREAD

**Issue by unnatixlr8** [kriscross07/atom-gpp-compiler#40] opened 2016-09-10 17:21 UTC
When I compile and run any c++ program, Gnome Terminal gives **"The child process exited normally with status 0."** message.

There is also a relaunch button at the end of the message.
This happens when "Hold the program" option is selected in Profile Preference.

**Comment by kriscross07** [comment] 2016-09-10 20:37
Duplicate of #31.

**Closed by kriscross07** 2016-09-10 20:37 UTC
